version: '3'

services:
  # master:
  #   image: osrf/ros:kinetic-desktop-full
  #   command: roscore
  #   networks:
  #     - ros
  gazebo:
    image: osrf/ros:kinetic-desktop-full
    command: roslaunch gazebo_ros empty_world.launch
    networks:
      - ros
    environment:
      DISPLAY: unix$DISPLAY
      # ROS_HOSTNAME: gazebo
      # ROS_MASTER_URI: http://master:11311
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri

networks:
  ros:
    driver: bridge
